[workspace]
channels = ["conda-forge"]
name = "MuJoCo-Lab"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
uv = "*"
git = "*"  # git clone을 위해 추가
nodejs = "*"

[tasks]
clone = "test -d mjlab || git clone https://github.com/mujocolab/mjlab.git"

setup = { depends-on = ["clone"], cmd = """
    cd mjlab && 
    uv sync
""" }

train = "cd mjlab && uv run train"
play = "cd mjlab && uv run play"
demo = "cd mjlab && uv run demo"
list_envs = "cd mjlab && uv run list_envs"
viz-nan = "cd mjlab && uv run viz-nan"